title: Sample Webpage
author: isdas8
email:isdas8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first time using GitHub. _Maybe_ this might become a proper **Project**.

# social links
twitter_username: isdas8
github_username:  isdas8

theme: minima 

show_excerpts: true # set to false to remove excerpts on the homepage
