theme: minima
title: Sample Webpage
author: isdas8
email:isdas8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first time using GitHub.This might become a proper Project.

# social links
twitter_username: isdas8
github_username:  isdas8



show_excerpts: true # set to false to remove excerpts on the homepage
